<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CoursesSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // Web Development Courses (Category 1, Instructor 2)
            [
                'title' => 'Complete Web Development Bootcamp',
                'slug' => 'complete-web-development-bootcamp',
                'short_description' => 'Learn HTML, CSS, JavaScript, and modern frameworks from scratch',
                'description' => 'This comprehensive course covers everything you need to become a professional web developer. From the basics of HTML and CSS to advanced JavaScript and popular frameworks like React and Vue.',
                'objectives' => json_encode(['Build responsive websites', 'Master JavaScript fundamentals', 'Create modern web applications', 'Deploy projects to production']),
                'requirements' => json_encode(['Basic computer skills', 'A computer with internet connection', 'Willingness to learn']),
                'category_id' => 1,
                'instructor_id' => 2,
                'level' => 'beginner',
                'language' => 'English',
                'price' => 49.99,
                'is_free' => 0,
                'status' => 'published',
                'is_featured' => 1,
                'total_duration' => 3600,
                'enrollment_count' => 156,
                'rating_average' => 4.7,
                'rating_count' => 89,
                'created_at' => date('Y-m-d H:i:s', strtotime('-60 days')),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Advanced Vue.js Masterclass',
                'slug' => 'advanced-vuejs-masterclass',
                'short_description' => 'Master Vue 3 Composition API, Pinia, and modern Vue development',
                'description' => 'Take your Vue.js skills to the next level with this advanced course covering Vue 3, Composition API, state management with Pinia, and best practices.',
                'objectives' => json_encode(['Master Vue 3 Composition API', 'Build scalable applications', 'Implement state management', 'Test Vue applications']),
                'requirements' => json_encode(['Basic JavaScript knowledge', 'Understanding of Vue basics', 'Node.js installed']),
                'category_id' => 1,
                'instructor_id' => 2,
                'level' => 'advanced',
                'language' => 'English',
                'price' => 79.99,
                'is_free' => 0,
                'status' => 'published',
                'is_featured' => 1,
                'total_duration' => 2400,
                'enrollment_count' => 89,
                'rating_average' => 4.9,
                'rating_count' => 56,
                'created_at' => date('Y-m-d H:i:s', strtotime('-45 days')),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Mobile Development Courses (Category 2, Instructor 3)
            [
                'title' => 'React Native - Build Mobile Apps',
                'slug' => 'react-native-build-mobile-apps',
                'short_description' => 'Create cross-platform mobile applications with React Native',
                'description' => 'Learn to build beautiful, performant mobile apps for both iOS and Android using React Native. Perfect for web developers looking to expand into mobile.',
                'objectives' => json_encode(['Build iOS and Android apps', 'Use React Native components', 'Integrate with APIs', 'Publish to app stores']),
                'requirements' => json_encode(['JavaScript fundamentals', 'Basic React knowledge', 'Mac for iOS development (optional)']),
                'category_id' => 2,
                'instructor_id' => 3,
                'level' => 'intermediate',
                'language' => 'English',
                'price' => 59.99,
                'is_free' => 0,
                'status' => 'published',
                'is_featured' => 1,
                'total_duration' => 3000,
                'enrollment_count' => 123,
                'rating_average' => 4.6,
                'rating_count' => 74,
                'created_at' => date('Y-m-d H:i:s', strtotime('-50 days')),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Data Science Courses (Category 3, Instructor 4)
            [
                'title' => 'Python for Data Science',
                'slug' => 'python-for-data-science',
                'short_description' => 'Master Python, NumPy, Pandas, and data visualization',
                'description' => 'Complete guide to using Python for data analysis and visualization. Learn the essential libraries and techniques used by data scientists worldwide.',
                'objectives' => json_encode(['Master Python basics', 'Use NumPy and Pandas', 'Create visualizations', 'Analyze real datasets']),
                'requirements' => json_encode(['No programming experience needed', 'Basic math knowledge']),
                'category_id' => 3,
                'instructor_id' => 4,
                'level' => 'beginner',
                'language' => 'English',
                'price' => 0,
                'is_free' => 1,
                'status' => 'published',
                'is_featured' => 1,
                'total_duration' => 2800,
                'enrollment_count' => 234,
                'rating_average' => 4.8,
                'rating_count' => 145,
                'created_at' => date('Y-m-d H:i:s', strtotime('-70 days')),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Machine Learning A-Z',
                'slug' => 'machine-learning-a-z',
                'short_description' => 'Complete guide to machine learning algorithms and applications',
                'description' => 'Learn machine learning from scratch with hands-on projects. Covers supervised learning, unsupervised learning, and neural networks.',
                'objectives' => json_encode(['Understand ML algorithms', 'Build ML models', 'Implement neural networks', 'Deploy ML applications']),
                'requirements' => json_encode(['Python knowledge', 'High school mathematics', 'Basic statistics']),
                'category_id' => 3,
                'instructor_id' => 4,
                'level' => 'intermediate',
                'language' => 'English',
                'price' => 89.99,
                'is_free' => 0,
                'status' => 'published',
                'is_featured' => 0,
                'total_duration' => 4200,
                'enrollment_count' => 167,
                'rating_average' => 4.5,
                'rating_count' => 98,
                'created_at' => date('Y-m-d H:i:s', strtotime('-55 days')),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Design Courses (Category 4, Instructor 3)
            [
                'title' => 'UI/UX Design Fundamentals',
                'slug' => 'ui-ux-design-fundamentals',
                'short_description' => 'Learn user interface and user experience design principles',
                'description' => 'Comprehensive course on UI/UX design covering design thinking, user research, wireframing, prototyping, and visual design.',
                'objectives' => json_encode(['Understand UX principles', 'Create wireframes', 'Design interfaces', 'Conduct user research']),
                'requirements' => json_encode(['No design experience needed', 'Figma account (free)']),
                'category_id' => 4,
                'instructor_id' => 3,
                'level' => 'beginner',
                'language' => 'English',
                'price' => 39.99,
                'is_free' => 0,
                'status' => 'published',
                'is_featured' => 1,
                'total_duration' => 2200,
                'enrollment_count' => 198,
                'rating_average' => 4.7,
                'rating_count' => 112,
                'created_at' => date('Y-m-d H:i:s', strtotime('-40 days')),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Business Course (Category 5, Instructor 2)
            [
                'title' => 'Start Your Own Business',
                'slug' => 'start-your-own-business',
                'short_description' => 'Complete guide to entrepreneurship and starting a business',
                'description' => 'Learn everything you need to start and grow a successful business, from idea validation to scaling and marketing.',
                'objectives' => json_encode(['Validate business ideas', 'Create business plans', 'Launch products', 'Scale businesses']),
                'requirements' => json_encode(['Entrepreneurial mindset', 'Willingness to take action']),
                'category_id' => 5,
                'instructor_id' => 2,
                'level' => 'beginner',
                'language' => 'English',
                'price' => 0,
                'is_free' => 1,
                'status' => 'published',
                'is_featured' => 0,
                'total_duration' => 1800,
                'enrollment_count' => 276,
                'rating_average' => 4.4,
                'rating_count' => 156,
                'created_at' => date('Y-m-d H:i:s', strtotime('-30 days')),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Marketing Course (Category 6, Instructor 3)
            [
                'title' => 'Digital Marketing Masterclass',
                'slug' => 'digital-marketing-masterclass',
                'short_description' => 'Master SEO, social media, email marketing, and paid ads',
                'description' => 'Complete digital marketing course covering all major channels and strategies to grow your business online.',
                'objectives' => json_encode(['Master SEO basics', 'Run social media campaigns', 'Create email funnels', 'Manage paid advertising']),
                'requirements' => json_encode(['Basic internet knowledge', 'Business or product to market (optional)']),
                'category_id' => 6,
                'instructor_id' => 3,
                'level' => 'intermediate',
                'language' => 'English',
                'price' => 49.99,
                'is_free' => 0,
                'status' => 'published',
                'is_featured' => 0,
                'total_duration' => 2600,
                'enrollment_count' => 145,
                'rating_average' => 4.6,
                'rating_count' => 87,
                'created_at' => date('Y-m-d H:i:s', strtotime('-25 days')),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Draft Course
            [
                'title' => 'Advanced TypeScript Programming',
                'slug' => 'advanced-typescript-programming',
                'short_description' => 'Master TypeScript for large-scale applications',
                'description' => 'Deep dive into TypeScript covering advanced types, generics, decorators, and architectural patterns.',
                'objectives' => json_encode(['Master TypeScript types', 'Use advanced generics', 'Implement design patterns']),
                'requirements' => json_encode(['JavaScript proficiency', 'Basic TypeScript knowledge']),
                'category_id' => 1,
                'instructor_id' => 2,
                'level' => 'advanced',
                'language' => 'English',
                'price' => 69.99,
                'is_free' => 0,
                'status' => 'draft',
                'is_featured' => 0,
                'total_duration' => 0,
                'enrollment_count' => 0,
                'rating_average' => 0,
                'rating_count' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('courses')->insertBatch($data);

        echo "Courses seeded successfully!\n";
    }
}
